[package]
name = "cast-core"
version = "1.5.0"
description = "Launcher logic"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
reqwest = { version = "0.13.1", features = ["json", "form", "multipart"] }
tokio = { version = "1", features = ["sync", "fs", "io-util", "time", "process", "rt", "macros"] }
zip = "7.2.0"
sha1 = "0.10"
sha2 = "0.10"
regex = "1"
uuid = { version = "1", features = ["v4"] }
url = "2"
tiny_http = "0.12"
# for copy modrinth
rusqlite = { version = "0.39", features = ["bundled"] }
png = "0.18"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
